name: Scrape NIFDC (2025 YTD)

on:
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install system deps
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential python3-dev libssl-dev libffi-dev libxml2-dev libxslt1-dev zlib1g-dev

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m playwright install --with-deps chromium

      - name: Run scraper
        run: python scraper.py

      - name: Commit CSVs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/raw_batches_2025YTD.csv data/weekly_market_share.csv || true
          if git diff --cached --quiet; then
            echo "No data changes to commit."
          else
            git commit -m "Update CSVs (Actions)"
            git push
          fi

      - name: Upload logs & screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: scrape-debug
          path: |
            logs/**
            screenshots/**

