name: Scrape NIFDC (2025 YTD)

on:
  workflow_dispatch: {}
  # schedule:
  #   - cron: "0 9 * * 1"

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m playwright install --with-deps chromium

      - name: Run scraper
        run: |
          python scraper.py

      - name: Commit CSVs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/raw_batches_2025YTD.csv data/weekly_market_share.csv || true
          if git diff --cached --quiet; then
            echo "No data changes to commit."
          else
            git commit -m "Update CSVs (Actions)"
            git push
          fi
      - name: Install HF client
        run: |
          python -m pip install --upgrade huggingface_hub

      - name: Push CSVs to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_SPACE_ID: ${{ secrets.HF_SPACE_ID }}
        run: |
          python - << 'PY'
from huggingface_hub import HfApi
import os
api = HfApi(token=os.environ["HF_TOKEN"])
space_id = os.environ["HF_SPACE_ID"]
# Upload both CSVs into the Space's data folder
api.upload_file(
    path_or_fileobj="data/raw_batches_2025YTD.csv",
    path_in_repo="data/raw_batches_2025YTD.csv",
    repo_id=space_id,
    repo_type="space"
)
api.upload_file(
    path_or_fileobj="data/weekly_market_share.csv",
    path_in_repo="data/weekly_market_share.csv",
    repo_id=space_id,
    repo_type="space"
)
print("✅ Uploaded CSVs to Space:", space_id)
PY
